
name: Deploy Sagemaker ECR

on:
  push:
      branches: [ main, development ]
  pull_request:

jobs:
  changed-files:
    name: Source File Diff
    runs-on: ubuntu-latest
    outputs:
      file-diff: ${{ steps.changes.outputs.file-diff }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          since_last_remote_commit: 'true'
          files: |
            container/*

      - name: Set Changed Files
        id: changes
        run: |
          echo "::set-output name=file-diff::${{ steps.changed-files.outputs.all_changed_files }}"

  set-regions:
    name: Set regions
    needs: changed-files

    if: ${{ needs.changed-files.outputs.file-diff }}
    outputs:
      regions: ${{ steps.set-regions.outputs.regions }}

    runs-on: ubuntu-latest
    steps:
    - name: Set regions
      id: set-regions
      run: |
        AWS_REGIONS=("ap-southeast-2" "us-east-1")
        AWS_REGIONS=$( for r in $AWS_REGIONS; do echo $r; done |  jq -Rsc '. / "\n" - [""]' )

        echo "::set-output name=regions::$AWS_REGIONS"
    

  build:
    name: Build and push ${{ matrix.region }}
    needs: set-regions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{fromJSON(needs.set-regions.outputs.regions)}}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set Github env var based on branch name
      id: set-environment
      run: |
        BRANCH_NAME=${{ github.head_ref }}
        echo $BRANCH_NAME
        if [[ $BRANCH_NAME == "master" ]]; then
          export ENVIRONMENT="production"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        elif [[ $BRANCH_NAME == "development" ]]; then
          export ENVIRONMENT="development"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        else
          export ENVIRONMENT="sandbox"
          export AWS_ACCESS_KEY_ID=${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
        fi

        echo $ENVIRONMENT

        echo "##[set-output name=environment;]$(echo $ENVIRONMENT)"
        echo "::set-output name=short-sha::$(git rev-parse --short ${{ github.sha }})"
        echo "::set-output name=aws_access_key_id::$(echo $AWS_ACCESS_KEY_ID)"
        echo "::set-output name=aws_secret_access_key::$(echo $AWS_SECRET_ACCESS_KEY)"

    - name: Build Docker image
      env:
        ECR_REPOSITORY: sagemaker-run-notebook
      run: 
        echo "Building docker image"

        cd $PWD/container && docker build -f Dockerfile -t $ECR_REPOSITORY .

          
    - name: Configure AWS credentials for ${{ matrix.region }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ steps.set-environment.outputs.aws_access_key_id }}
        aws-secret-access-key: ${{ steps.set-environment.outputs.aws_secret_access_key }}
        aws-region: ${{ matrix.region }}

    - name: Login to Amazon ECR ${{ matrix.region }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and push image to Amazon ECR ${{ matrix.region }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sagemaker-run-notebook
        IMAGE_TAG: ${{ steps.set-environment.outputs.environment }}-${{ steps.set-environment.outputs.short-sha }}  ## Change to {branch}-0.0.0
        IMAGE_LATEST_TAG: ${{ steps.set-environment.outputs.environment }}-latest                                   ## Change to {branch}-latest
      run: |
        IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY"

        echo "Pushing docker image to $IMAGE_URI"
        echo "$IMAGE_URI:$IMAGE_TAG"

        echo "$IMAGE_URI:$IMAGE_LATEST_TAG"
        docker image tag $ECR_REPOSITORY "$IMAGE_URI:$IMAGE_TAG"
        docker image tag $ECR_REPOSITORY "$IMAGE_URI:$IMAGE_LATEST_TAG"

        # docker image push "$IMAGE_URI:$IMAGE_TAG"
        # docker image push "$IMAGE_URI:$IMAGE_LATEST_TAG"

        docker image push --all-tags "$IMAGE_URI"
